"""信源库种子数据：90 个渠道 + 19 条政策文档记录。

数据来源：《城市更新政策官方网址.md》（2026-07-31 人工核实）。
原则：只收录 MD 明确点名的政策文件；发文号/日期/链接未知一律留空，
并在 note 中标注"待人工核验"——不允许虚构（PRD 核心红线）。
渠道表与 crawler/sources.py 必须同步（tests/test_sourcelib_seed.py 强制）。
"""
from sourcelib.models import Channel, PolicyDocument

# ---------------------------------------------------------------- 渠道（90）

# 国家层面（8）：6 个主站 + 财政部办公厅 + 发改委投资项目在线平台（MD 正文内嵌）
_CHANNELS = [
    Channel("govcn", "国务院", "中国政府网·政策文件库", "https://www.gov.cn/zhengce/zhengceku/",
            "national", False, "政策库；发布《城市更新“十五五”规划》(国发〔2026〕12号)、《持续推进城市更新行动的意见》"),
    Channel("mohurd", "住房和城乡建设部", "住房城乡建设部官网", "https://www.mohurd.gov.cn",
            "national", False, "城市更新行动牵头主管部门；发布防止大拆大建通知、第一批/第二批试点城市名单、可复制经验做法清单、中央财政支持城市更新行动联合通知"),
    Channel("mnr", "自然资源部", "自然资源部官网", "https://www.mnr.gov.cn",
            "national", False, "发布《支持城市更新的规划与土地政策指引(2023版)》、自然资发〔2025〕226号"),
    Channel("mof", "财政部", "财政部官网", "https://www.mof.gov.cn",
            "national", False, "办公厅发布《关于开展2026年度中央财政支持实施城市更新行动的通知》(财办建〔2026〕14号)"),
    Channel("mof-bgt", "财政部办公厅", "财政部办公厅官网", "https://bgt.mof.gov.cn",
            "national", False, "发布《关于开展2026年度中央财政支持实施城市更新行动的通知》(财办建〔2026〕14号)"),
    Channel("ndrc", "国家发展和改革委员会", "国家发展改革委官网", "https://www.ndrc.gov.cn",
            "national", False, "投资项目审批、中央预算内投资；投资项目在线审批监管平台 https://www.tzxm.gov.cn"),
    Channel("ndrc-tzxm", "国家发展和改革委员会", "国家投资项目在线审批监管平台", "https://www.tzxm.gov.cn",
            "national", False, "投资项目在线审批监管平台"),
    Channel("scio", "国务院新闻办公室", "国新办官网", "https://www.scio.gov.cn",
            "national", False, "政策例行吹风会，解读《城市更新“十五五”规划》等"),
    # 北京市（20）：市级专栏/主页 4 + 区政府站 16（第一批试点）
    Channel("bj-portal", "北京市人民政府", "首都之窗·北京城市更新专栏", "https://www.beijing.gov.cn/fuwu/lqfw/ztzl/bjchshgx/index.html",
            "city", True, "汇总国家+北京市全部城市更新政策文件；挂《北京市城市更新政策激励工具箱(1.0版)》通知链接、《北京市城市更新条例》等"),
    Channel("bj-zjw", "市住房城乡建设委", "市住建委官网", "https://zjw.beijing.gov.cn",
            "city", True, "《北京市城市更新政策激励工具箱(1.0版)》(2026-01-01)的发布/代章主体"),
    Channel("bj-zjw-csgx", "市住房城乡建设委", "市住建委·城市更新主题分类", "https://zjw.beijing.gov.cn/bjjs/xxgk/zcwj2024/aztfl64/csgx/index.shtml",
            "city", True, "汇总全部配套政策、项目库与专家委员会管理办法"),
    Channel("bj-ghzrzyw", "市规划自然资源委", "市规自委官网", "https://ghzrzyw.beijing.gov.cn",
            "city", True, "《深化建筑规模管理激励城市更新的管理规定》等配套政策与解读"),
    Channel("bj-dc", "东城区人民政府", "东城区政府门户", "http://www.bjdch.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-xc", "西城区人民政府", "西城区政府门户", "http://www.bjxch.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-cy", "朝阳区人民政府", "朝阳区政府门户", "http://www.bjchy.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-hd", "海淀区人民政府", "海淀区政府门户", "https://www.bjhd.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-ft", "丰台区人民政府", "丰台区政府门户", "http://www.bjft.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-sjs", "石景山区人民政府", "石景山区政府门户", "http://www.bjsjs.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-mtg", "门头沟区人民政府", "门头沟区政府门户", "http://www.bjmtg.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-fs", "房山区人民政府", "房山区政府门户", "http://www.bjfsh.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-tz", "通州区人民政府", "通州区政府门户", "http://www.bjtzh.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息（城市副中心相关更新政策）"),
    Channel("bj-sy", "顺义区人民政府", "顺义区政府门户", "https://www.bjshy.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-cp", "昌平区人民政府", "昌平区政府门户", "http://www.bjchp.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-dx", "大兴区人民政府", "大兴区政府门户", "http://www.bjdx.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-hr", "怀柔区人民政府", "怀柔区政府门户", "http://www.bjhr.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-pg", "平谷区人民政府", "平谷区政府门户", "http://www.bjpg.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-my", "密云区人民政府", "密云区政府门户", "http://www.bjmy.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    Channel("bj-yq", "延庆区人民政府", "延庆区政府门户", "http://www.bjyq.gov.cn",
            "district", False, "本区城市更新、老旧小区改造、街区更新、房屋征收等区级政策与项目信息"),
    # 天津市
    Channel("tj-zjw", "天津市住房城乡建设委员会", "天津市住建委官网", "http://zfcxjs.tj.gov.cn",
            "city", False, "城市更新、老旧小区改造等政策与项目信息"),
    # 河北省
    Channel("he-zjw", "河北省住房和城乡建设厅", "河北省住建厅官网", "http://zfcxjst.hebei.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("ts-zjw", "唐山市住房和城乡建设局", "唐山市住建局官网", "https://zhujianju.tangshan.gov.cn",
            "city", True, "第一批试点；《唐山市城市更新实施办法》(唐政发〔2025〕4号) 发布与解读、城市更新项目信息"),
    # 山西省
    Channel("sx-zjw", "山西省住房和城乡建设厅", "山西省住建厅官网", "http://zjt.shanxi.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 内蒙古自治区
    Channel("nm-zjw", "内蒙古自治区住房和城乡建设厅", "内蒙古住建厅官网", "http://zjt.nmg.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("hhht-zjw", "呼和浩特市住房和城乡建设局", "呼和浩特市住建局官网", "http://zfcxjsj.huhhot.gov.cn",
            "city", True, "第一批试点；《呼和浩特市城市更新实施办法（暂行）》及专项规划、项目信息"),
    # 辽宁省
    Channel("ln-zjw", "辽宁省住房和城乡建设厅", "辽宁省住建厅官网", "http://zjt.ln.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("sy-zjw", "沈阳市城乡建设局", "沈阳市城乡建设局官网", "https://jw.shenyang.gov.cn",
            "city", True, "第一批试点；城市更新相关政策"),
    # 吉林省
    Channel("jl-zjw", "吉林省住房和城乡建设厅", "吉林省住建厅官网", "http://jst.jl.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 黑龙江省
    Channel("hlj-zjw", "黑龙江省住房和城乡建设厅", "黑龙江省住建厅官网", "http://zfcxjst.hlj.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 上海市
    Channel("sh-portal", "上海市人民政府", "上海市政府门户", "https://www.shanghai.gov.cn",
            "city", False, "政策文件检索；《上海市城市更新条例》《上海市城市更新行动方案(2023—2025年)》"),
    Channel("sh-ghzyj", "市规划资源局", "上海市规划资源局官网", "https://ghzyj.sh.gov.cn",
            "city", False, "《上海市城市更新指引》《集中推进城市更新高质量发展的规划资源实施意见(2025版)》"),
    # 江苏省
    Channel("js-zjw", "江苏省住房和城乡建设厅", "江苏省住建厅官网", "http://jsszfhcxjst.jiangsu.gov.cn",
            "provincial", False, "《关于进一步支持城市更新行动的若干政策措施》；城市体检、老旧小区改造"),
    Channel("nj-zjw", "南京市城乡建设委员会", "南京市建委官网", "http://sjw.nanjing.gov.cn",
            "city", True, "第一批试点；城市更新专栏，《南京市城市更新办法》"),
    Channel("suz-zjw", "苏州市住房和城乡建设局", "苏州市住建局官网", "http://zfcjj.suzhou.gov.cn",
            "city", True, "第一批试点；城市更新相关政策"),
    # 浙江省
    Channel("zj-zjw", "浙江省住房和城乡建设厅", "浙江省住建厅官网", "http://jst.zj.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造、“好房子”建设等政策"),
    Channel("nb-zjw", "宁波市住房和城乡建设局", "宁波市住建局官网", "https://zjw.ningbo.gov.cn",
            "city", True, "第一批试点；城市更新、老旧小区改造相关政策与项目信息"),
    Channel("hz-zjw", "杭州市城乡建设委员会", "杭州市建委官网", "http://cxjw.hangzhou.gov.cn",
            "city", False, "设城市更新处、城市更新促进中心；《杭州市城市更新条例》、首轮三年行动"),
    # 安徽省
    Channel("ah-zjw", "安徽省住房和城乡建设厅", "安徽省住建厅官网", "http://dohurd.ah.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("cz-zjw", "滁州市住房和城乡建设局", "滁州市住建局官网", "https://zfcxjsj.chuzhou.gov.cn",
            "city", True, "第一批试点；《滁州市实施城市更新行动推动城市高质量发展实施方案》、城市生命线安全工程"),
    Channel("tl-zjw", "铜陵市住房和城乡建设局", "铜陵市住建局官网", "https://zfcxjsj.tl.gov.cn",
            "city", True, "第一批试点；城市更新、老旧小区改造相关政策与项目信息"),
    # 福建省
    Channel("fj-zjw", "福建省住房和城乡建设厅", "福建省住建厅官网", "http://zjt.fujian.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("xm-zjw", "厦门市住房和建设局", "厦门市住建局官网", "https://szjj.xm.gov.cn",
            "city", True, "第一批试点；城市更新、老旧小区改造相关政策与项目信息"),
    # 江西省
    Channel("jx-zjw", "江西省住房和城乡建设厅", "江西省住建厅官网", "http://zjt.jiangxi.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("nc-zjw", "南昌市住房和城乡建设局", "南昌市住建局官网", "https://zjj.nc.gov.cn",
            "city", True, "第一批试点；城市更新专栏汇总示范项目、城中村改造、完整社区建设政策"),
    Channel("nc-zjw-csgx", "南昌市住房和城乡建设局", "南昌市住建局·城市更新专栏", "https://zjj.nc.gov.cn/nczfbzglj/csgx",
            "city", True, "第一批试点；示范项目、城中村改造、完整社区建设政策"),
    Channel("jdz-zjw", "景德镇市住房和城乡建设局", "景德镇市住建局官网", "http://zjj.jdz.gov.cn",
            "city", True, "第一批试点；城市更新专项规划、老城保护与传统风貌更新政策"),
    # 山东省
    Channel("sd-zjw", "山东省住房和城乡建设厅", "山东省住建厅官网", "http://zjt.shandong.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("yt-zjw", "烟台市住房和城乡建设局", "烟台市住建局官网", "https://zjj.yantai.gov.cn",
            "city", True, "第一批试点；城市更新相关政策、历史街区有机更新经验"),
    Channel("wf-zjw", "潍坊市住房和城乡建设局", "潍坊市住建局官网", "https://jsj.weifang.gov.cn",
            "city", True, "第一批试点；城市更新、老旧小区改造、海绵城市相关政策与项目信息"),
    # 河南省
    Channel("hn-zjw", "河南省住房和城乡建设厅", "河南省住建厅官网", "https://hnjs.henan.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 湖北省
    Channel("hb-zjw", "湖北省住房和城乡建设厅", "湖北省住建厅官网", "http://zjt.hubei.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("hs-zjw", "黄石市住房和城市更新局", "黄石市住建局官网", "http://zjj.huangshi.gov.cn",
            "city", True, "第一批试点；机构更名“住房和城市更新局”，设城市更新专题，发布“十五五”规划、历史文化名城保护办法"),
    # 湖南省
    Channel("hun-zjw", "湖南省住房和城乡建设厅", "湖南省住建厅官网", "http://zjt.hunan.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("cs-zjw", "长沙市住房和城乡建设局", "长沙市住建局官网", "https://szjw.changsha.gov.cn",
            "city", True, "第一批试点；城市更新、城中村改造相关政策"),
    # 广东省
    Channel("gd-zjw", "广东省住房和城乡建设厅", "广东省住建厅官网", "http://zfcxjst.gd.gov.cn",
            "provincial", False, "省级城市更新、城中村改造等政策；《广东省城市更新条例》"),
    Channel("gz-zjw", "广州市住房和城乡建设局", "广州市住建局官网", "https://zfcj.gz.gov.cn",
            "city", False, "城市更新专栏；《广州市城市更新条例》《广州市城市更新专项规划(2021—2035年)》"),
    Channel("gz-zjw-csgx", "广州市住房和城乡建设局", "广州市住建局·城市更新专栏", "https://zfcj.gz.gov.cn/zjyw/csgx",
            "city", False, "《广州市城市更新条例》《广州市城市更新专项规划(2021—2035年)》"),
    Channel("sz-zjj", "深圳市住房和建设局", "深圳市住建局官网", "https://zjj.sz.gov.cn",
            "city", False, "《关于规范城市更新实施工作的若干意见》(深建规〔2025〕4号)"),
    Channel("sz-pnr", "深圳市规划和自然资源局", "深圳市规自局官网", "https://pnr.sz.gov.cn",
            "city", False, "《进一步规范城市更新规划土地管理的若干措施(试行)》(深规划资源规〔2025〕5号)、城市更新“十四五”规划"),
    Channel("sz-portal", "深圳市人民政府", "深圳市政府门户", "https://www.sz.gov.cn",
            "city", False, "《深圳市国土空间总体规划(2021—2035年)》《深圳经济特区城市更新条例》等"),
    # 广西壮族自治区
    Channel("gx-zjw", "广西壮族自治区住房和城乡建设厅", "广西住建厅官网", "http://zjt.gxzf.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 海南省
    Channel("hai-zjw", "海南省住房和城乡建设厅", "海南省住建厅官网", "http://zjt.hainan.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 重庆市（第一批试点范围仅渝中区、九龙坡区）
    Channel("cq-zjw", "重庆市住房和城乡建设委员会", "重庆市住建委官网", "https://zfcxjw.cq.gov.cn",
            "city", True, "第一批试点（范围仅渝中区、九龙坡区）；城市更新管理办法与项目计划"),
    Channel("cq-yz", "渝中区人民政府", "渝中区政府门户", "https://www.cqyz.gov.cn",
            "district", True, "第一批试点区；区级城市更新、老旧小区改造、历史街区保护更新政策"),
    Channel("cq-jlp", "九龙坡区人民政府", "九龙坡区政府门户", "https://www.cqjlp.gov.cn",
            "district", True, "第一批试点区；区级城市更新、老旧小区改造、老旧工业区改造政策"),
    # 四川省
    Channel("sc-zjw", "四川省住房和城乡建设厅", "四川省住建厅官网", "http://jst.sc.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("cd-zjw", "成都市住房和城乡建设局", "成都市住建局官网", "http://cdzj.chengdu.gov.cn",
            "city", True, "第一批试点；城市更新、老旧小区改造、城市体检相关政策与项目信息"),
    # 贵州省
    Channel("gz-zfcxjst", "贵州省住房和城乡建设厅", "贵州省住建厅官网", "http://zfcxjst.guizhou.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 云南省
    Channel("yn-zjw", "云南省住房和城乡建设厅", "云南省住建厅官网", "https://zfcxjst.yn.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 西藏自治区
    Channel("xz-zjw", "西藏自治区住房和城乡建设厅", "西藏住建厅官网", "http://zjt.xizang.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 陕西省
    Channel("shx-zjw", "陕西省住房和城乡建设厅", "陕西省住建厅官网", "http://js.shaanxi.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("xa-zjw", "西安市住房和城乡建设局", "西安市住建局官网", "https://zjj.xa.gov.cn",
            "city", True, "第一批试点；城市更新、老旧小区改造相关政策"),
    # 甘肃省
    Channel("gs-zjw", "甘肃省住房和城乡建设厅", "甘肃省住建厅官网", "https://zjt.gansu.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 青海省
    Channel("qh-zjw", "青海省住房和城乡建设厅", "青海省住建厅官网", "http://zjt.qinghai.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 宁夏回族自治区
    Channel("nx-zjw", "宁夏回族自治区住房和城乡建设厅", "宁夏住建厅官网", "http://jst.nx.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    Channel("yc-zjw", "银川市住房和城乡建设局", "银川市住建局官网", "https://zjj.yinchuan.gov.cn",
            "city", True, "第一批试点；城市更新、老旧小区改造相关政策与项目信息"),
    # 新疆维吾尔自治区
    Channel("xj-zjw", "新疆维吾尔自治区住房和城乡建设厅", "新疆住建厅官网", "https://zjt.xinjiang.gov.cn",
            "provincial", False, "省级城市更新、老旧小区改造等政策与项目信息"),
    # 新疆生产建设兵团
    Channel("xjbt-zjw", "新疆生产建设兵团住房和城乡建设局", "兵团住建局官网", "http://jshbj.xjbt.gov.cn",
            "provincial", False, "兵团城市更新、老旧小区改造相关政策与项目信息"),
    # 城市更新融资支持平台（3）
    Channel("cdb", "国家开发银行", "国家开发银行官网", "https://www.cdb.cn",
            "finance", False, "城市更新专项贷款等政策性金融支持；2025年城市更新领域投放约7863亿元"),
    Channel("cpppc", "财政部政府和社会资本合作中心", "财政部PPP中心官网", "https://www.cpppc.org",
            "finance", False, "PPP项目库与城市更新相关PPP项目信息发布；城市更新项目投融资参考"),
    Channel("adbc", "中国农业发展银行", "中国农业发展银行官网", "https://www.adbc.com.cn",
            "finance", False, "政策性银行；与国开行并列长期低息贷款支持城市更新/“三大工程”（保障性住房、城中村改造、“平急两用”公共基础设施）"),
]

# ------------------------------------------------------------ 政策文档（19）
_DOCUMENTS = [
    # 国家层面（10）
    PolicyDocument("n-155-guihua", "《城市更新“十五五”规划》", "国发〔2026〕12号",
                   channel_id="govcn", keywords=("城市更新", "十五五", "规划", "更新"),
                   note="国务院发布"),
    PolicyDocument("n-shishi-yijian", "持续推进城市更新行动的意见",
                   channel_id="govcn", keywords=("城市更新", "行动", "意见"),
                   note="全称与发文号待人工核验"),
    PolicyDocument("n-fangzhi-dachaidajian", "防止大拆大建通知",
                   channel_id="mohurd", keywords=("大拆大建", "城市更新"),
                   note="住建部发布，全称与发文号待人工核验"),
    PolicyDocument("n-dian-shidian-1", "第一批城市更新试点城市名单", "建办科函〔2021〕443号",
                   channel_id="mohurd", keywords=("试点", "名单", "城市更新"),
                   note="第一批试点城市/部门共 24 处"),
    PolicyDocument("n-dian-shidian-2", "第二批城市更新试点城市名单",
                   channel_id="mohurd", keywords=("试点", "名单", "城市更新"),
                   note="发文号待人工核验"),
    PolicyDocument("n-jingyan-qingdan", "城市更新可复制经验做法清单",
                   channel_id="mohurd", keywords=("经验", "做法", "清单"),
                   note="分批次发布"),
    PolicyDocument("n-caizheng-zhichi", "中央财政支持城市更新行动联合通知",
                   channel_id="mohurd", keywords=("中央财政", "支持", "城市更新"),
                   note="住建部与财政部联合发布，全称与发文号待人工核验"),
    PolicyDocument("n-tudi-zhidao-2023", "支持城市更新的规划与土地政策指引（2023版）",
                   channel_id="mnr", keywords=("规划", "土地", "指引"),
                   note="自然资源部发布"),
    PolicyDocument("n-zrzfb-2025-226", "关于进一步支持城市更新行动若干措施的通知", "自然资发〔2025〕226号",
                   channel_id="mnr", keywords=("城市更新", "措施", "支持"),
                   note="自然资源部发布"),
    PolicyDocument("n-czb-2026-14", "关于开展2026年度中央财政支持实施城市更新行动的通知", "财办建〔2026〕14号",
                   channel_id="mof", keywords=("中央财政", "2026", "城市更新"),
                   note="财政部办公厅发布"),
    # 北京市（8）
    PolicyDocument("bj-csgx-tiaoli", "北京市城市更新条例",
                   channel_id="bj-portal", keywords=("北京", "城市更新", "条例"),
                   note="生效日期待人工核验"),
    PolicyDocument("bj-csgx-gongjuxiang", "关于印发《北京市城市更新政策激励工具箱（1.0版）》的通知",
                   effective_date="2026-01-01",
                   channel_id="bj-portal", keywords=("北京", "工具箱", "激励", "容积率", "奖励"),
                   note="发布日期 2026-01-01（据网址清单）；全称以原文为准"),
    PolicyDocument("bj-jianzhu-guimo", "深化建筑规模管理激励城市更新的管理规定",
                   channel_id="bj-ghzrzyw", keywords=("北京", "建筑规模", "容积率", "激励"),
                   note="发文号待人工核验"),
    PolicyDocument("bj-guihua-tiaoli", "北京市城乡规划条例",
                   keywords=("北京", "规划", "条例"),
                   note="PRD 附录B参考文件，发布渠道待补充"),
    PolicyDocument("bj-xingdong-jihua", "北京市城市更新行动计划",
                   channel_id="bj-portal", keywords=("北京", "行动", "计划"),
                   note="全称与发文号待人工核验"),
    PolicyDocument("bj-zhuanti-guihua", "北京市城市更新专项规划",
                   channel_id="bj-portal", keywords=("北京", "专项规划"),
                   note="名称与发文号待人工核验"),
    PolicyDocument("bj-xiangmu-ku", "城市更新项目库管理办法",
                   channel_id="bj-zjw", keywords=("北京", "项目库", "管理"),
                   note="名称待人工核验"),
    PolicyDocument("bj-shijian-ditu", "城市更新最佳实践项目地图",
                   channel_id="bj-portal", keywords=("北京", "实践", "地图"),
                   note="工具类产品，非正式文件"),
    # 政策解读（1）
    PolicyDocument("scio-jiedu-155", "《城市更新“十五五”规划》政策例行吹风会解读",
                   channel_id="scio", keywords=("解读", "十五五", "城市更新"),
                   note="解读材料，非正式文件"),
]

CHANNELS: list[Channel] = _CHANNELS
DOCUMENTS: list[PolicyDocument] = _DOCUMENTS
